version: '3.8'

services:
  flask_app:
    image: flask_qr_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - static-data:/app/static
    command: ["python", "app.py"]


volumes:
  static-data:

networks:
  default:
    external: True
      name: flask_app_default
